
openapi: 3.0.0
info:
  title: mamat-api 
  description: API documentation for mamat-api
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
    description: Local development server
paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Server is healthy
  /api/v2/data:
    get:
      summary: Get sample data
      responses:
        '200':
          description: Successful response
